#!/usr/bin/env python3
"""Regenerate assets/deploy-button.svg.

A one-shot design tool, not part of any build: nothing in CI runs it, and the SVG it writes is
the committed artifact. It exists because the label is OUTLINED rather than set as <text>, which
is what keeps the button a fixed width on every machine (and is what Railway, Zeabur and Sealos
all do with theirs). Outlines cannot be edited by hand, so changing the wording, the size or the
face means running this again.

Requires, none of them repo dependencies:

    python3 -m venv .venv && .venv/bin/pip install fonttools brotli uharfbuzz
    npm pack @fontsource/inter && tar xzf fontsource-inter-*.tgz

Then, from this directory:

    .venv/bin/python make-deploy-button.py package/files/inter-latin-500-normal.woff2

harfbuzz does the shaping so the letter spacing matches what a browser would produce from the
same font, kerning included. Inter is the brand face and is licensed under the SIL OFL 1.1,
which is what makes embedding its outlines here redistributable.
"""
import re
import subprocess
import sys
import tempfile
from pathlib import Path

import uharfbuzz as hb
from fontTools.misc.transform import Transform
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont

LABEL = "Deploy on InstaCloud"
FONT_SIZE = 15.0          # cap height lands at 10.91px, matching the reference buttons' ~11px
HEIGHT = 40.0
RADIUS = 6.0
PAD_LEFT = 12.0           # Railway's own padding: icon at x=12, label at x=47, 12px to the right
GAP = 11.0
PAD_RIGHT = 12.0
ICON_HEIGHT = 20.0
ICON_BOX = (28.0909, 24.0004)   # bbox of ICON_PATH below

# The cloud mark, taken verbatim from insta-landing/public/deploy-badge.svg, which took it from
# brand/instacloud-wordmark.svg. Same glyph as the badge instacloud.com already serves.
ICON_PATH = (
    "M25.8353 10.9281C25.339 10.2783 24.71 9.73231 24 9.32911V0H0V16.487H5.0087V15.6522C5.0087 "
    "13.8111 6.50671 12.313 8.34783 12.313H9.18261V11.4783C9.18261 10.0291 9.74692 8.6663 10.772 "
    "7.6416C11.7967 6.6169 13.1595 6.05217 14.6087 6.05217C16.0579 6.05217 17.4207 6.61649 "
    "18.4454 7.6416C18.7964 7.99263 19.0923 8.38163 19.3315 8.80403C18.7972 8.96807 18.288 "
    "9.21141 17.8272 9.53363C16.219 10.6268 15.2314 12.6808 15.6555 14.6108C15.8099 13.9329 "
    "16.0483 13.2893 16.4131 12.7C17.2512 11.3297 18.7054 10.3847 20.279 10.2574C22.7599 10.0136 "
    "24.9813 11.9078 25.0856 14.4029C25.1954 16.8271 23.2858 18.8519 20.8721 18.9917C20.8712 "
    "18.9917 20.8708 18.9917 20.87 18.9917H0V24.0004H24V19.9142C27.1722 18.1398 28.0909 13.8795 "
    "25.8353 10.9286V10.9281Z"
)


def outline(font_path: Path, text: str, size: float) -> tuple[str, float, float]:
    """Shape `text` and return (single path d, advance width, cap height), baseline at y=0."""
    # harfbuzz cannot read woff2, so hand it a ttf either way.
    if font_path.suffix == ".woff2":
        tmp = Path(tempfile.mkdtemp()) / "font.ttf"
        f = TTFont(font_path)
        f.flavor = None
        f.save(tmp)
        font_path = tmp

    face = hb.Face(hb.Blob(font_path.read_bytes()))
    hb_font = hb.Font(face)
    buf = hb.Buffer()
    buf.add_str(text)
    buf.guess_segment_properties()
    hb.shape(hb_font, buf)

    tt = TTFont(font_path)
    glyphs = tt.getGlyphSet()
    order = tt.getGlyphOrder()
    scale = size / tt["head"].unitsPerEm

    parts, x = [], 0.0
    for info, pos in zip(buf.glyph_infos, buf.glyph_positions):
        pen = SVGPathPen(glyphs, ntos=lambda v: f"{v:.2f}")
        # Font units go up, SVG goes down, so y is flipped and the baseline sits at y=0.
        glyphs[order[info.codepoint]].draw(
            TransformPen(pen, Transform(scale, 0, 0, -scale,
                                        x + pos.x_offset * scale, -pos.y_offset * scale))
        )
        if pen.getCommands():
            parts.append(pen.getCommands())
        x += pos.x_advance * scale
    return " ".join(parts), x, tt["OS/2"].sCapHeight * scale


def main() -> None:
    font = Path(sys.argv[1] if len(sys.argv) > 1 else "package/files/inter-latin-500-normal.woff2")
    text_d, text_w, cap_h = outline(font, LABEL, FONT_SIZE)

    icon_scale = ICON_HEIGHT / ICON_BOX[1]
    icon_w = ICON_BOX[0] * icon_scale
    text_x = PAD_LEFT + icon_w + GAP
    width = text_x + text_w + PAD_RIGHT
    icon_y = (HEIGHT - ICON_HEIGHT) / 2
    baseline = (HEIGHT + cap_h) / 2   # centred on cap height, as the reference buttons are

    svg = f"""<svg xmlns="http://www.w3.org/2000/svg" width="{width:.0f}" height="{HEIGHT:.0f}" viewBox="0 0 {width:.0f} {HEIGHT:.0f}" role="img" aria-label="{LABEL}">
  <title>{LABEL}</title>
  <!--
    Generated by assets/make-deploy-button.py. The label is outlined, so do not edit it by hand:
    change the constants in that script and run it again.

    One file covers both themes, swapped by a prefers-color-scheme rule INSIDE the SVG rather than
    by a <picture> around it. The README this button lives in is also served by the template
    gallery, whose markdown renderer parses no raw HTML on purpose, so there is no <picture> to
    reach for. An SVG referenced from <img> still evaluates the query against the viewer's own
    system setting, which is how templates/pi/logo.svg already covers light and dark with one
    asset. A renderer that ignores the query keeps the light palette, so the fallback is brand
    black. Without the rule the black button all but vanishes on a dark README.

    Geometry follows the one-click buttons this sits beside (Railway 183x40 r6, Sealos 185x42
    r6.7, Zeabur 172x36 r8): {HEIGHT:.0f} tall, {RADIUS:.0f} radius, {PAD_LEFT:.0f}/{GAP:.0f}/{PAD_RIGHT:.0f} padding. It is wider than
    those only because "{LABEL}" is four characters longer than "Deploy on Railway".

    Label: Inter Medium (SIL OFL 1.1, the brand face) shaped with harfbuzz at {FONT_SIZE:.0f}px,
    cap height {cap_h:.2f}px.
  -->
  <style>
    .bg {{ fill: #0A0A0A }}
    .fg {{ fill: #FAFAFA }}
    @media (prefers-color-scheme: dark) {{
      .bg {{ fill: #FAFAFA }}
      .fg {{ fill: #0A0A0A }}
    }}
  </style>
  <rect class="bg" width="{width:.0f}" height="{HEIGHT:.0f}" rx="{RADIUS:.0f}"/>
  <g class="fg" transform="translate({PAD_LEFT:.0f} {icon_y:.0f}) scale({icon_scale:.6f})">
    <path d="{ICON_PATH}"/>
  </g>
  <path class="fg" transform="translate({text_x:.2f} {baseline:.2f})" d="{text_d}"/>
</svg>
"""
    out = Path(__file__).with_name("deploy-button.svg")
    out.write_text(svg)
    print(f"{out.name}: {width:.0f}x{HEIGHT:.0f} r{RADIUS:.0f}, label {text_w:.2f}px, cap {cap_h:.2f}px")


if __name__ == "__main__":
    main()
